//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 17.0.33906.96
// 
namespace Gmach.MyProjectService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MUser", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class MUser : Gmach.MyProjectService.BaseEntity {
        
        private string FirstLastNameField;
        
        private bool IsNeemanField;
        
        private string Phone1Field;
        
        private string Phone2Field;
        
        private string UserIDField;
        
        private string uAddressField;
        
        private string uMailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName {
            get {
                return this.FirstLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstLastNameField, value) != true)) {
                    this.FirstLastNameField = value;
                    this.RaisePropertyChanged("FirstLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNeeman {
            get {
                return this.IsNeemanField;
            }
            set {
                if ((this.IsNeemanField.Equals(value) != true)) {
                    this.IsNeemanField = value;
                    this.RaisePropertyChanged("IsNeeman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uAddress {
            get {
                return this.uAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.uAddressField, value) != true)) {
                    this.uAddressField = value;
                    this.RaisePropertyChanged("uAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uMail {
            get {
                return this.uMailField;
            }
            set {
                if ((object.ReferenceEquals(this.uMailField, value) != true)) {
                    this.uMailField = value;
                    this.RaisePropertyChanged("uMail");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gmach.MyProjectService.Payment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gmach.MyProjectService.Loan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gmach.MyProjectService.Neeman))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gmach.MyProjectService.Donation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gmach.MyProjectService.MUser))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Payment : Gmach.MyProjectService.BaseEntity {
        
        private bool PaidField;
        
        private bool ReturnedCheckField;
        
        private Gmach.MyProjectService.Loan pAskField;
        
        private int pCodeField;
        
        private System.DateTime pDateField;
        
        private int pReturnedSumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Paid {
            get {
                return this.PaidField;
            }
            set {
                if ((this.PaidField.Equals(value) != true)) {
                    this.PaidField = value;
                    this.RaisePropertyChanged("Paid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnedCheck {
            get {
                return this.ReturnedCheckField;
            }
            set {
                if ((this.ReturnedCheckField.Equals(value) != true)) {
                    this.ReturnedCheckField = value;
                    this.RaisePropertyChanged("ReturnedCheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gmach.MyProjectService.Loan pAsk {
            get {
                return this.pAskField;
            }
            set {
                if ((object.ReferenceEquals(this.pAskField, value) != true)) {
                    this.pAskField = value;
                    this.RaisePropertyChanged("pAsk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pCode {
            get {
                return this.pCodeField;
            }
            set {
                if ((this.pCodeField.Equals(value) != true)) {
                    this.pCodeField = value;
                    this.RaisePropertyChanged("pCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime pDate {
            get {
                return this.pDateField;
            }
            set {
                if ((this.pDateField.Equals(value) != true)) {
                    this.pDateField = value;
                    this.RaisePropertyChanged("pDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pReturnedSum {
            get {
                return this.pReturnedSumField;
            }
            set {
                if ((this.pReturnedSumField.Equals(value) != true)) {
                    this.pReturnedSumField = value;
                    this.RaisePropertyChanged("pReturnedSum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Loan : Gmach.MyProjectService.BaseEntity {
        
        private bool AllLoanReturnedField;
        
        private string Arev1Field;
        
        private string Arev2Field;
        
        private System.DateTime AskDateField;
        
        private Gmach.MyProjectService.MUser BorrowerField;
        
        private bool ConfirmedField;
        
        private System.DateTime FirstPaymentField;
        
        private int LCodeField;
        
        private int LSumField;
        
        private Gmach.MyProjectService.Neeman NeemanField;
        
        private int PaymentsNumField;
        
        private string PaymentsTypeField;
        
        private System.DateTime RequestedDateField;
        
        private string VerbalSumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllLoanReturned {
            get {
                return this.AllLoanReturnedField;
            }
            set {
                if ((this.AllLoanReturnedField.Equals(value) != true)) {
                    this.AllLoanReturnedField = value;
                    this.RaisePropertyChanged("AllLoanReturned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arev1 {
            get {
                return this.Arev1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Arev1Field, value) != true)) {
                    this.Arev1Field = value;
                    this.RaisePropertyChanged("Arev1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arev2 {
            get {
                return this.Arev2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Arev2Field, value) != true)) {
                    this.Arev2Field = value;
                    this.RaisePropertyChanged("Arev2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AskDate {
            get {
                return this.AskDateField;
            }
            set {
                if ((this.AskDateField.Equals(value) != true)) {
                    this.AskDateField = value;
                    this.RaisePropertyChanged("AskDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gmach.MyProjectService.MUser Borrower {
            get {
                return this.BorrowerField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerField, value) != true)) {
                    this.BorrowerField = value;
                    this.RaisePropertyChanged("Borrower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Confirmed {
            get {
                return this.ConfirmedField;
            }
            set {
                if ((this.ConfirmedField.Equals(value) != true)) {
                    this.ConfirmedField = value;
                    this.RaisePropertyChanged("Confirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FirstPayment {
            get {
                return this.FirstPaymentField;
            }
            set {
                if ((this.FirstPaymentField.Equals(value) != true)) {
                    this.FirstPaymentField = value;
                    this.RaisePropertyChanged("FirstPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LCode {
            get {
                return this.LCodeField;
            }
            set {
                if ((this.LCodeField.Equals(value) != true)) {
                    this.LCodeField = value;
                    this.RaisePropertyChanged("LCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LSum {
            get {
                return this.LSumField;
            }
            set {
                if ((this.LSumField.Equals(value) != true)) {
                    this.LSumField = value;
                    this.RaisePropertyChanged("LSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gmach.MyProjectService.Neeman Neeman {
            get {
                return this.NeemanField;
            }
            set {
                if ((object.ReferenceEquals(this.NeemanField, value) != true)) {
                    this.NeemanField = value;
                    this.RaisePropertyChanged("Neeman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentsNum {
            get {
                return this.PaymentsNumField;
            }
            set {
                if ((this.PaymentsNumField.Equals(value) != true)) {
                    this.PaymentsNumField = value;
                    this.RaisePropertyChanged("PaymentsNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentsType {
            get {
                return this.PaymentsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsTypeField, value) != true)) {
                    this.PaymentsTypeField = value;
                    this.RaisePropertyChanged("PaymentsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestedDate {
            get {
                return this.RequestedDateField;
            }
            set {
                if ((this.RequestedDateField.Equals(value) != true)) {
                    this.RequestedDateField = value;
                    this.RaisePropertyChanged("RequestedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerbalSum {
            get {
                return this.VerbalSumField;
            }
            set {
                if ((object.ReferenceEquals(this.VerbalSumField, value) != true)) {
                    this.VerbalSumField = value;
                    this.RaisePropertyChanged("VerbalSum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Neeman", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Neeman : Gmach.MyProjectService.BaseEntity {
        
        private int nCodeField;
        
        private string nCommunityField;
        
        private string nFirstLastNameField;
        
        private string nPhone1Field;
        
        private string nPhone2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nCode {
            get {
                return this.nCodeField;
            }
            set {
                if ((this.nCodeField.Equals(value) != true)) {
                    this.nCodeField = value;
                    this.RaisePropertyChanged("nCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nCommunity {
            get {
                return this.nCommunityField;
            }
            set {
                if ((object.ReferenceEquals(this.nCommunityField, value) != true)) {
                    this.nCommunityField = value;
                    this.RaisePropertyChanged("nCommunity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nFirstLastName {
            get {
                return this.nFirstLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.nFirstLastNameField, value) != true)) {
                    this.nFirstLastNameField = value;
                    this.RaisePropertyChanged("nFirstLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nPhone1 {
            get {
                return this.nPhone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.nPhone1Field, value) != true)) {
                    this.nPhone1Field = value;
                    this.RaisePropertyChanged("nPhone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nPhone2 {
            get {
                return this.nPhone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.nPhone2Field, value) != true)) {
                    this.nPhone2Field = value;
                    this.RaisePropertyChanged("nPhone2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Donation", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Donation : Gmach.MyProjectService.BaseEntity {
        
        private string BankNameField;
        
        private string BankNumField;
        
        private string DonorField;
        
        private int dCodeField;
        
        private System.DateTime dDateField;
        
        private int dSumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankNum {
            get {
                return this.BankNumField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNumField, value) != true)) {
                    this.BankNumField = value;
                    this.RaisePropertyChanged("BankNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Donor {
            get {
                return this.DonorField;
            }
            set {
                if ((object.ReferenceEquals(this.DonorField, value) != true)) {
                    this.DonorField = value;
                    this.RaisePropertyChanged("Donor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dCode {
            get {
                return this.dCodeField;
            }
            set {
                if ((this.dCodeField.Equals(value) != true)) {
                    this.dCodeField = value;
                    this.RaisePropertyChanged("dCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dDate {
            get {
                return this.dDateField;
            }
            set {
                if ((this.dDateField.Equals(value) != true)) {
                    this.dDateField = value;
                    this.RaisePropertyChanged("dDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dSum {
            get {
                return this.dSumField;
            }
            set {
                if ((this.dSumField.Equals(value) != true)) {
                    this.dSumField = value;
                    this.RaisePropertyChanged("dSum");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyProjectService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUsers", ReplyAction="http://tempuri.org/IService/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.MUser>> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUser", ReplyAction="http://tempuri.org/IService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(Gmach.MyProjectService.MUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUser", ReplyAction="http://tempuri.org/IService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(Gmach.MyProjectService.MUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(Gmach.MyProjectService.MUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByID", ReplyAction="http://tempuri.org/IService/GetUserByIDResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.MUser> GetUserByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserNeeman", ReplyAction="http://tempuri.org/IService/UserNeemanResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.MUser>> UserNeemanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserNeeman", ReplyAction="http://tempuri.org/IService/GetUserNeemanResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.MUser> GetUserNeemanAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByName", ReplyAction="http://tempuri.org/IService/GetUserByNameResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.MUser> GetUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPayments", ReplyAction="http://tempuri.org/IService/GetPaymentsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Payment>> GetPaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPayment", ReplyAction="http://tempuri.org/IService/AddPaymentResponse")]
        System.Threading.Tasks.Task AddPaymentAsync(Gmach.MyProjectService.Payment newPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdatePayment", ReplyAction="http://tempuri.org/IService/UpdatePaymentResponse")]
        System.Threading.Tasks.Task UpdatePaymentAsync(Gmach.MyProjectService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePayment", ReplyAction="http://tempuri.org/IService/DeletePaymentResponse")]
        System.Threading.Tasks.Task DeletePaymentAsync(Gmach.MyProjectService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPaymentByCode", ReplyAction="http://tempuri.org/IService/GetPaymentByCodeResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.Payment> GetPaymentByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLoan", ReplyAction="http://tempuri.org/IService/GetLoanResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddLoan", ReplyAction="http://tempuri.org/IService/AddLoanResponse")]
        System.Threading.Tasks.Task AddLoanAsync(Gmach.MyProjectService.Loan newLoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateLoan", ReplyAction="http://tempuri.org/IService/UpdateLoanResponse")]
        System.Threading.Tasks.Task UpdateLoanAsync(Gmach.MyProjectService.Loan loan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteLoan", ReplyAction="http://tempuri.org/IService/DeleteLoanResponse")]
        System.Threading.Tasks.Task DeleteLoanAsync(Gmach.MyProjectService.Loan loan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLoanByCode", ReplyAction="http://tempuri.org/IService/GetLoanByCodeResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.Loan> GetLoanByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLoanById", ReplyAction="http://tempuri.org/IService/GetLoanByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanByIdAsync(Gmach.MyProjectService.MUser u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLoanByUser", ReplyAction="http://tempuri.org/IService/GetLoanByUserResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanByUserAsync(Gmach.MyProjectService.MUser u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPaymentByLoan", ReplyAction="http://tempuri.org/IService/GetPaymentByLoanResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Payment>> GetPaymentByLoanAsync(Gmach.MyProjectService.Loan l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLoanForConfirm", ReplyAction="http://tempuri.org/IService/GetLoanForConfirmResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanForConfirmAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ArchivedLoans", ReplyAction="http://tempuri.org/IService/ArchivedLoansResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> ArchivedLoansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDonation", ReplyAction="http://tempuri.org/IService/GetDonationResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Donation>> GetDonationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDonation", ReplyAction="http://tempuri.org/IService/AddDonationResponse")]
        System.Threading.Tasks.Task AddDonationAsync(Gmach.MyProjectService.Donation newDonation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateDonation", ReplyAction="http://tempuri.org/IService/UpdateDonationResponse")]
        System.Threading.Tasks.Task UpdateDonationAsync(Gmach.MyProjectService.Donation donation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDonation", ReplyAction="http://tempuri.org/IService/DeleteDonationResponse")]
        System.Threading.Tasks.Task DeleteDonationAsync(Gmach.MyProjectService.Donation donation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDonationByCode", ReplyAction="http://tempuri.org/IService/GetDonationByCodeResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.Donation> GetDonationByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetNeeman", ReplyAction="http://tempuri.org/IService/GetNeemanResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Neeman>> GetNeemanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNeeman", ReplyAction="http://tempuri.org/IService/AddNeemanResponse")]
        System.Threading.Tasks.Task AddNeemanAsync(Gmach.MyProjectService.Neeman newNeeman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateNeeman", ReplyAction="http://tempuri.org/IService/UpdateNeemanResponse")]
        System.Threading.Tasks.Task UpdateNeemanAsync(Gmach.MyProjectService.Neeman neeman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteNeeman", ReplyAction="http://tempuri.org/IService/DeleteNeemanResponse")]
        System.Threading.Tasks.Task DeleteNeemanAsync(Gmach.MyProjectService.Neeman neeman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetNeemanByCode", ReplyAction="http://tempuri.org/IService/GetNeemanByCodeResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.Neeman> GetNeemanByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetNeemanByName", ReplyAction="http://tempuri.org/IService/GetNeemanByNameResponse")]
        System.Threading.Tasks.Task<Gmach.MyProjectService.Neeman> GetNeemanByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPaymentByUser", ReplyAction="http://tempuri.org/IService/GetPaymentByUserResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Payment>> GetPaymentByUserAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Gmach.MyProjectService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Gmach.MyProjectService.IService>, Gmach.MyProjectService.IService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.MUser>> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Threading.Tasks.Task AddUserAsync(Gmach.MyProjectService.MUser newUser) {
            return base.Channel.AddUserAsync(newUser);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(Gmach.MyProjectService.MUser user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(Gmach.MyProjectService.MUser user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.MUser> GetUserByIDAsync(string id) {
            return base.Channel.GetUserByIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.MUser>> UserNeemanAsync() {
            return base.Channel.UserNeemanAsync();
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.MUser> GetUserNeemanAsync(string name) {
            return base.Channel.GetUserNeemanAsync(name);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.MUser> GetUserByNameAsync(string name) {
            return base.Channel.GetUserByNameAsync(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Payment>> GetPaymentsAsync() {
            return base.Channel.GetPaymentsAsync();
        }
        
        public System.Threading.Tasks.Task AddPaymentAsync(Gmach.MyProjectService.Payment newPayment) {
            return base.Channel.AddPaymentAsync(newPayment);
        }
        
        public System.Threading.Tasks.Task UpdatePaymentAsync(Gmach.MyProjectService.Payment payment) {
            return base.Channel.UpdatePaymentAsync(payment);
        }
        
        public System.Threading.Tasks.Task DeletePaymentAsync(Gmach.MyProjectService.Payment payment) {
            return base.Channel.DeletePaymentAsync(payment);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.Payment> GetPaymentByCodeAsync(int code) {
            return base.Channel.GetPaymentByCodeAsync(code);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanAsync() {
            return base.Channel.GetLoanAsync();
        }
        
        public System.Threading.Tasks.Task AddLoanAsync(Gmach.MyProjectService.Loan newLoan) {
            return base.Channel.AddLoanAsync(newLoan);
        }
        
        public System.Threading.Tasks.Task UpdateLoanAsync(Gmach.MyProjectService.Loan loan) {
            return base.Channel.UpdateLoanAsync(loan);
        }
        
        public System.Threading.Tasks.Task DeleteLoanAsync(Gmach.MyProjectService.Loan loan) {
            return base.Channel.DeleteLoanAsync(loan);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.Loan> GetLoanByCodeAsync(int code) {
            return base.Channel.GetLoanByCodeAsync(code);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanByIdAsync(Gmach.MyProjectService.MUser u) {
            return base.Channel.GetLoanByIdAsync(u);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanByUserAsync(Gmach.MyProjectService.MUser u) {
            return base.Channel.GetLoanByUserAsync(u);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Payment>> GetPaymentByLoanAsync(Gmach.MyProjectService.Loan l) {
            return base.Channel.GetPaymentByLoanAsync(l);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> GetLoanForConfirmAsync() {
            return base.Channel.GetLoanForConfirmAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Loan>> ArchivedLoansAsync() {
            return base.Channel.ArchivedLoansAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Donation>> GetDonationAsync() {
            return base.Channel.GetDonationAsync();
        }
        
        public System.Threading.Tasks.Task AddDonationAsync(Gmach.MyProjectService.Donation newDonation) {
            return base.Channel.AddDonationAsync(newDonation);
        }
        
        public System.Threading.Tasks.Task UpdateDonationAsync(Gmach.MyProjectService.Donation donation) {
            return base.Channel.UpdateDonationAsync(donation);
        }
        
        public System.Threading.Tasks.Task DeleteDonationAsync(Gmach.MyProjectService.Donation donation) {
            return base.Channel.DeleteDonationAsync(donation);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.Donation> GetDonationByCodeAsync(int code) {
            return base.Channel.GetDonationByCodeAsync(code);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Neeman>> GetNeemanAsync() {
            return base.Channel.GetNeemanAsync();
        }
        
        public System.Threading.Tasks.Task AddNeemanAsync(Gmach.MyProjectService.Neeman newNeeman) {
            return base.Channel.AddNeemanAsync(newNeeman);
        }
        
        public System.Threading.Tasks.Task UpdateNeemanAsync(Gmach.MyProjectService.Neeman neeman) {
            return base.Channel.UpdateNeemanAsync(neeman);
        }
        
        public System.Threading.Tasks.Task DeleteNeemanAsync(Gmach.MyProjectService.Neeman neeman) {
            return base.Channel.DeleteNeemanAsync(neeman);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.Neeman> GetNeemanByCodeAsync(int code) {
            return base.Channel.GetNeemanByCodeAsync(code);
        }
        
        public System.Threading.Tasks.Task<Gmach.MyProjectService.Neeman> GetNeemanByNameAsync(string name) {
            return base.Channel.GetNeemanByNameAsync(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gmach.MyProjectService.Payment>> GetPaymentByUserAsync(string id) {
            return base.Channel.GetPaymentByUserAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServices/Service/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService,
        }
    }
}
